security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: username
                password_parameter: password
                default_target_path: passe_commande_index
            http_basic:
                realm: Secured Area
            entry_point: form_login
            remember_me:
                # case « Se souvenir de moi » de la page de connexion
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 jours
                path: /
            logout:
                path: app_logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/pain, roles: ROLE_USER }
        - { path: ^/jour, roles: ROLE_USER }
        - { path: ^/synthese/1, roles: ROLE_USER }
        - { path: ^/synthese/2, roles: ROLE_USER }
        - { path: ^/synthesepoids, roles: ROLE_USER }
        - { path: ^/register, roles: ROLE_USER }
        - { path: ^/settings, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/livree, roles: ROLE_USER }
